### ISSUE TITLE
Failing to parse module

### ISSUE THREAD

**Issue by mritzman-dg** [Esri/node-arcgis#83]
I installed the 'arcgis' module via npm hoping to use it in a ReactJS application I'm working on.  After installing this I'm seeing the error below when trying to run webpack-dev-server.  Note that if I'm remove the 'arcgis' module everything works as expected.  I'm running on Windows 7 as well if that helps.

ERROR in ./~/entities/maps/entities.json
Module parse failed: C:\Users\mritzman\Development\search_discovery_app\node_modules\entities\maps\entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\mritzman\Development\search_discovery_app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/sanitize-html/~/htmlparser2/lib/Tokenizer.js 4:16-54

ERROR in ./~/entities/maps/legacy.json
Module parse failed: C:\Users\mritzman\Development\search_discovery_app\node_modules\entities\maps\legacy.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\mritzman\Development\search_discovery_app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/sanitize-html/~/htmlparser2/lib/Tokenizer.js 5:16-52

ERROR in ./~/entities/maps/xml.json
Module parse failed: C:\Users\mritzman\Development\search_discovery_app\node_modules\entities\maps\xml.json Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\mritzman\Development\search_discovery_app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/sanitize-html/~/htmlparser2/lib/Tokenizer.js 6:16-49

ERROR in ./~/entities/maps/decode.json
Module parse failed: C:\Users\mritzman\Development\search_discovery_app\node_modules\entities\maps\decode.json Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:4)
    at Parser.pp$4.raise (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\mritzman\Development\search_discovery_app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\mritzman\Development\search_discovery_app\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/entities/lib/decode_codepoint.js 1:16-46

**Comment by jgravois** [comment]
i can reproduce this.  

substituting 'dist/**browser**/index.js' as the package.json [`main`]() property resolves the error, but lord knows how you'd actually use an already browserified version of the library *that way*, even in a vanilla JS app.

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="node_modules/arcgis/dist/browser/index.js"></script>
  </head>
  <body>
    console.log(ArcGIS) // no bueno
  </body>
</html>
```

**Comment by mritzman-dg** [comment]
Thanks for your feedback @jgravois.  Yeah, I don't know who to use it either.

**Comment by nikolaswise** [comment]
@mritzman-dg looks like the lib isn't being parsed into a node module properly. The browser one will work if you attach it to the window, but probably not be workable from your app.

I'm taking a peek at the building from `lib` to `dist` right now, since it would be nice to use this in apps for sure.
